apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-storage-clair
  namespace: quay-enterprise
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi 
  storageClassName: quay-storageclass
