apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
  namespace: quay-enterprise
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: registry.access.redhat.com/rhscl/postgresql-10-rhel7:1-35
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
          - name: POSTGRESQL_USER
            valueFrom: 
              secretKeyRef:
                name: quay-database-credential
                key: database-username
          - name: POSTGRESQL_DATABASE
            valueFrom: 
              secretKeyRef:
                name: quay-database-credential
                key: database-name
          - name: POSTGRESQL_PASSWORD
            valueFrom: 
              secretKeyRef:
                name: quay-database-credential
                key: database-password
          volumeMounts:
            - mountPath: /var/lib/pgsql/data
              name: postgredb
      serviceAccount: postgres
      serviceAccountName: postgres
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-storage
