---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: quay-storageclass
parameters: 
  type: gp2
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete

### To encrypt volume add following lines
#encrypted: "true"
#fsType: xfs (or other fs)
#kmsKeyId:
