ACTION_LOG_ARCHIVE_LOCATION: default
ACTION_LOG_ARCHIVE_PATH: /var/log
ACTION_LOG_ROTATION_THRESHOLD: 2w
AUTHENTICATION_TYPE: Database
BITTORRENT_FILENAME_PEPPER: f71bfbaa-d523-442d-9d0f-753072d46f7a
BUILDLOGS_REDIS:
  host: 172.30.23.17
  password: quay
  port: 6379
CONTACT_INFO:
- http://santander.com
- mailto:fandrade@redhat.com
- tel:+55 11 97428-0221
DATABASE_SECRET_KEY: '55061001134732240436951635213325782955764556434284892476712926041169685348432'
DB_URI: postgresql://quay:quay@172.30.83.235/quay-enterprise
DEFAULT_TAG_EXPIRATION: 2w
DISTRIBUTED_STORAGE_CONFIG:
  default:
  - LocalStorage
  - storage_path: /datastorage/registry
DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS: []
DISTRIBUTED_STORAGE_PREFERENCE:
- default
ENTERPRISE_LOGO_URL: https://www.meioemensagem.com.br/wp-content/uploads/2018/03/Santander_NovaMarca_575.png
EXTERNAL_TLS_TERMINATION: true
FEATURE_ACI_CONVERSION: false
FEATURE_ACTION_LOG_ROTATION: true
FEATURE_ANONYMOUS_ACCESS: true
FEATURE_APP_REGISTRY: false
FEATURE_APP_SPECIFIC_TOKENS: true
FEATURE_BUILD_SUPPORT: false
FEATURE_CHANGE_TAG_EXPIRATION: true
FEATURE_DIRECT_LOGIN: true
FEATURE_GITHUB_LOGIN: true
FEATURE_MAILING: true
FEATURE_PARTIAL_USER_AUTOCOMPLETE: true
FEATURE_REPO_MIRROR: false
FEATURE_REQUIRE_TEAM_INVITE: true
FEATURE_RESTRICTED_V1_PUSH: true
FEATURE_SECURITY_NOTIFICATIONS: true
FEATURE_SECURITY_SCANNER: true
FEATURE_TEAM_SYNCING: true
FEATURE_USERNAME_CONFIRMATION: true
FEATURE_USER_CREATION: true
FEATURE_USER_LOG_ACCESS: true
GITHUB_LOGIN_CONFIG:
  API_ENDPOINT: https://api.github.com/
  CLIENT_ID: 175dba86a807612803d9
  CLIENT_SECRET: 5373a869f8a9e2fa27e15d932a8fa14edbfbaf04
  GITHUB_ENDPOINT: https://github.com/
  LOGIN_BINDING_FIELD: username
  ORG_RESTRICT: false
GITHUB_TRIGGER_CONFIG: {}
GITLAB_TRIGGER_KIND: {}
GPG2_PRIVATE_KEY_FILENAME: signing-private.gpg
GPG2_PUBLIC_KEY_FILENAME: signing-public.gpg
LDAP_ADMIN_DN: uid=admin,cn=users,cn=compat,dc=example,dc=com
LDAP_ADMIN_PASSWD: redhat*99
LDAP_BASE_DN:
- cn=compat
- dc=example
- dc=com
LDAP_EMAIL_ATTR: mail
LDAP_UID_ATTR: uid
LDAP_URI: ldap://ldapurl.com
LDAP_USER_RDN:
- cn=users
LOG_ARCHIVE_LOCATION: default
MAIL_DEFAULT_SENDER: support@example.com
MAIL_PASSWORD: smtppass
MAIL_PORT: 587
MAIL_SERVER: smtpserver.example.com
MAIL_USERNAME: smtpuser
MAIL_USE_AUTH: true
MAIL_USE_TLS: false
PREFERRED_URL_SCHEME: https
REGISTRY_TITLE: Red Hat Quay
REGISTRY_TITLE_SHORT: Red Hat Quay
REPO_MIRROR_SERVER_HOSTNAME: null
REPO_MIRROR_TLS_VERIFY: true
SECRET_KEY: '83412484169985078673232702594764753873389678034264673119250730074815983250435'
SECURITY_SCANNER_ENDPOINT: https://quay-enterprise-clair.quay-enterprise.svc:6060
SECURITY_SCANNER_ISSUER_NAME: security_scanner
SERVER_HOSTNAME: quay.apps.myocp.sandbox664.opentlc.com
SETUP_COMPLETE: true
SIGNING_ENGINE: gpg2
TAG_EXPIRATION_OPTIONS:
- 0s
- 1d
- 1w
- 2w
- 4w
TEAM_RESYNC_STALE_TIME: 60m
TESTING: false
USERFILES_LOCATION: default
USERFILES_PATH: userfiles/
USER_EVENTS_REDIS:
  host: 172.30.23.17
  password: quay
  port: 6379
USE_CDN: false
V3_UPGRADE_MODE: complete
